""" Codebook for REF 2021 data """


COL_INST_NAME = "Institution name"
COL_OUTPUT_TITLE = "Title"
COL_OUTPUT_PLACE = "Place"
COL_OUTPUT_PUBLISHER = "Publisher"
COL_OUTPUT_VOL_TITLE = "Volume title"
COL_OUTPUT_VOL_NO = "Volume"
COL_OUTPUT_ISSUE = "Issue"
COL_OUTPUT_FIRST_PAGE = "First page"
COL_OUTPUT_ARTICLE_NO = "Article number"
COL_OUTPUT_ISBN = "ISBN"
COL_OUTPUT_ISSN = "ISSN"
COL_OUTPUT_DOI = "DOI"
COL_OUTPUT_PATENT_NO = "Patent number"
COL_OUTPUT_MONTH = "Month"
COL_OUTPUT_URL = "URL"
COL_OUTPUT_SUPP = "Supplementary information"
COL_IMPACT_SUMMARY = "1. Summary of the impact"
COL_IMPACT_DETAILS = "4. Details of the impact"

CATEGORY_FIELDS_EXCLUDE_CHARTS = []

FILEDS_TO_NOT_DISPLAY = [
    COL_OUTPUT_TITLE,
    COL_OUTPUT_PUBLISHER,
    COL_OUTPUT_ISBN,
    COL_OUTPUT_ISSN,
    COL_OUTPUT_DOI,
    COL_OUTPUT_PATENT_NO,
    COL_OUTPUT_URL,
    COL_OUTPUT_PLACE,
    COL_OUTPUT_VOL_NO,
    COL_OUTPUT_VOL_TITLE,
    COL_OUTPUT_ISSUE,
    COL_OUTPUT_FIRST_PAGE,
    COL_OUTPUT_ARTICLE_NO,
    COL_OUTPUT_MONTH,
    COL_OUTPUT_SUPP,
    COL_IMPACT_SUMMARY,
    COL_IMPACT_DETAILS,
]

ADDED_SUFFIXES = ["(added)", "(binned)"]
